name: Job Track Now

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    container: node:20
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Make env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_LOG_LEVEL: "DEBUG"
          envkey_REACT_APP_LOG_FILE: "portal.log"
          envkey_REACT_APP_ENABLE_CONSOLE_LOGGING: false
          envkey_REACT_APP_API_BASE_URL: "https://api.jobtracknow.net"
          envkey_REACT_APP_FRONTEND_BASE_URL: "https://jobtracknow.net"
          envkey_REACT_APP_OAUTH_REDIRECT_CALLBACK: "https://jobtracknow.net/callback"
          file_name: '.env'

      - name: disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV

      - name: install dependencies
        run: npm install

      - name: compile the code
        run: npm run build

      - name: copy files to web server
        uses: appleboy/scp-action@v1
        with:
          host: "54.208.82.135"
          username: "deploy"
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: "22"
          source: "./build/"
          target: "/var/www/jobtracknow/"

